name: Publish Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ] # mainブランチへのPRでもチェックは走らせたいよね

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check formatting and lint
        run: npm run format
      - name: Build
        run: npm run build
      # - name: Test
      #   run: npm test # テストコマンドをここに記述

  publish-gpr:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions: # GitHub Packages への書き込み権限が必要
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js for GPR publish
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://npm.pkg.github.com/'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build # 公開前にもビルドを実行
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}